sources:
  - MatrixSans-Regular.ufo
  - MatrixSans-Screen.ufo
  - MatrixSans-Print.ufo
  - MatrixSans-Video.ufo
  - MatrixSans-Raster.ufo
familyName: Matrix Sans
buildVariable: false
removeOutlineOverlaps: false
autohintTTF: false